// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlccnxspsqihbjvutjln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY2NueHNwc3FpaGJqdnV0amxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjgxNDEsImV4cCI6MjA3MTkwNDE0MX0.0raMybx3-k7y4PYU_te1Zq1hq1Rhvj00xpoYIi9riH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});